### ISSUE TITLE
Update the get-the-add-on icon

### ISSUE THREAD

**Issue by jobisoft** [thunderbird/webext-support#73]
https://github.com/thunderbird/webext-support/blob/master/images/get-the-addon.svg is using the old Thunderbird logo, would be cool if we could use the new Thunderbird logo!

**Comment by laurelterlesky** [comment]
Revised add on badge, compliments of @micahilbery 

![get_the_addon_badge_1 0 0](https://github.com/user-attachments/assets/fda8da73-192c-4e09-9f7a-15fc8c54bb2b)

[Figma file for reference](https://www.figma.com/design/iJiSR24OEGMrGJGHnX71GV/MarCom_2024_Q3_TBAddOnsBadge_v01.0.0?node-id=4012-13&t=tFRP9PtMkWEjern8-1)

**Comment by laurelterlesky** [comment]
Ready, compliments of @micahilbery 

[addon_badge.zip](https://github.com/user-attachments/files/16985564/addon_badge.zip)

**Comment by jobisoft** [comment]
Thanks for your support! The new icon is beautiful!
