### ISSUE TITLE
notifyTools gone

### ISSUE THREAD

**Issue by mlazdans** [thunderbird/webext-support#75]
Hello!

I'm not sure why notifyTools has been removed? Is there a better way now how to communicate back from experiments to webextension? Thanks!

**Comment by jobisoft** [comment]
The tools did not have the intended effect, they did not help developers to move on with their conversion from blob-experiments to dedicated experiments. Instead, they added complexity and held developers back. We do not want to advertise their usage any more.

Do you have a specific issue we can look into?

**Comment by mlazdans** [comment]
I was sending notifications from experiment side to webextension when user [clicked on message pane] that was initialized in experiment code (https://github.com/mlazdans/qnote/blob/ad9bb7333819fd9bd5f68087e60df28aa5b8cb2e/api/qapp.js#L644). I see this probably now could be implemented via messsgapane content script using messaging API in latest TB versions. Just wondering when I ever need to notify webextension from experiments what is now suggested approach. Thanks!

**Comment by jobisoft** [comment]
The correct approach is:

1. Identify if the UI of your add-on can be changed to be triggered by existing WebExtension UI elements:
* action buttons
* context menus
* content scripts

2. Create a dedicated WebExtension Experiment Event to be triggered by your own UI requirements
